### ISSUE TITLE
API Vélhop

### ISSUE THREAD

**Issue by Rudloff** [strasbourg/documentation#6]
J'avais créé pour StrasWeb une version JSON de l'API Vélhop : https://strasweb.fr/velhop/getJSON.php
Ça pourrait être bien d'avoir la même chose dans strasbourg-data.
Je peux essayer de l'implémenter mais je ne suis pas très à l'aise en Ruby.
(Le code original en PHP est disponible ici : https://svn.strasweb.fr/filedetails.php?repname=StrasWeb&path=%2Fvelhop%2FgetJSON.php)

**Comment by barodeur** [comment]
Merci @Rudloff, je viens de d'écrire une petite version du proxy, c'est dispo à l'adresse http://velhop.api.strasbourg-data.fr/ et le code source est là https://github.com/strasbourg/velhop-api (node.js)
